# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'gam | grok.no'
tagline:             "miscellaneous musings on software engineering, life and philosophy"
description:         'A slightly odd whatchammacallit'
url:                 http://gam.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Geir Amdal
  url:               https://twitter.com/infosophy
  email:             gam@grok.no

# Custom vars
version:             1.0.0
